### ISSUE TITLE
create a "pi" folder under /storage partition with pi.pi permissions

### ISSUE THREAD

**Issue by carmelopellegrino** [MechanicalVentilatorMilano/upgrade#7]
would be very helpful to have a folder, called `pi` or other name, at the top of the third partition (that mounted under `/storage`), where the `pi` user has all permissions.

It would be also very helpful to have the zeroes file deleted. For helping the compression would be enough to create it, `sync`ing the fs and then having it deleted.

**Comment by gennadiyalekseevitch** [comment]
added to the Raspbian OS v6 image.
